server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    appname: 注册中心

  client:
    registerWithEureka: false #单点的时候设置为false 禁止注册自身
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eurake/
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000
