server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eureka-demo-client-1
